#define CHORDAL_HOLD
#define FLOW_TAP_TERM 150
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY


#define AUDIO_PIN C6
#define AUDIO_INIT_DELAY
#define NO_MUSIC_MODE // Save 2000 bytes
//#define STARTUP_SONG SONG( { 2000.0f, 22 }, { 1000.0f, 18 } )
#define EE_HANDS
#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
