#define AUDIO_PIN C6
//#define AUDIO_INIT_DELAY
#define STARTUP_SONG SONG( { 2000.0f, 22 }, { 1000.0f, 18 } )
#define MOUSEKEY_INTERVAL 25
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 20
#define MOUSEKEY_MAX_SPEED 3
